### ISSUE TITLE
关于如何在单机上跑通测试

### ISSUE THREAD

**Issue by hezuojiao** [HustAIsGroup/CDBTune#1]
您好，我在尝试将在单机上跑你们的代码，但是environment/configs.py里的代码是空白的，以及environment.Server类并没有看到实现部分。你是否能提供configs.py的样例配置模版以及详细的单机测试流程？

Thanks!

**Comment by HustAIsGroup** [comment]
感谢您的关注！
1. environment/configs.py的模板如下：
# -*- coding: utf-8 -*-

"""
description: MySQL Database Configurations
"""

instance_config = {
    'tencent_cdb': {
        'server_url': '',
        'instance_id': '',
        'host': '',
        'port': ,
        'passwd': '',
        'user': '',
        'operator': '',
        'memory': 
    },
}

2. 上传的代码主要是在Tencent CDB上进行实现，请您参考environment.TencentServer的实现
3. 我们会尽快完善实现和测试指引，感谢理解。同时，我们正在与腾讯团队进行产品化该系统，相信你在不就后可以进行体验。感谢您的关注，如有问题持续保持联系。

**Comment by hezuojiao** [comment]
emmm...我发现现在的代码应该并不是完整的，里面一些参数对不上，并且还存在一些在使用的函数没实现的问题，希望你们后期能把代码整合一下，并给出测试文档😀，我从论文上看你们的工作做的挺有意思👏👍🏻
