### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by zjuKeLiu** [HustAIsGroup/CDBTune#10]
I have a question about the paper, why the performance of CDBTune is much worse than other algorithm in figure 5?

**Comment by ghost** [comment]
> I have a question about the paper, why the performance of CDBTune is much worse than other algorithm in figure 5?

I see the figure 5 in the paper, and the performance of CDBTune is better than the others. May be you got it wrong?

**Comment by zjuKeLiu** [comment]
Sorry to bother U. I misunderstood the legend. And thanks for your reply.
