### ISSUE TITLE
关于源码的一个问题

### ISSUE THREAD

**Issue by F-Rockman** [HustAIsGroup/CDBTune#16]
在ddpg.py文件中第287行，OUProcess代表的是什么？我没有找到相关实现，希望能够帮忙解答一下，谢谢。

**Comment by LiuYi-D** [comment]
> 在ddpg.py文件中第287行，OUProcess代表的是什么？我没有找到相关实现，希望能够帮忙解答一下，谢谢。

请问您现在问题解决了吗，我刚开始搭建这个项目，遇到了一些问题，想向你请教，能否留个联系方式？  我的qq  1027442600

**Comment by PlanningByCai** [comment]
refer to: https://github.com/TsinghuaDatabaseGroup/AI4DBCode/blob/master/DBTunner/src-CDBTune/AutoTuner/models/OUProcess.py

**Comment by F-Rockman** [comment]
> refer to: https://github.com/TsinghuaDatabaseGroup/AI4DBCode/blob/master/DBTunner/src-CDBTune/AutoTuner/models/OUProcess.py

thank you
